### ISSUE TITLE
Icicle-processor is missing from bintray.com

### ISSUE THREAD

**Issue by nielsdelporte** [segunfamisa/icicle#8]
Hi,

I would love to use this library in my project to simplify instance state management, but I cannot find the processor library on bintray even though I followed the readme to the letter.
Surfing to the website reveals that that folder indeed only possesses a metadata xml, but no pom and jar file.

Is the publishing still underway (had the problem yesterday as well)?

> Error:Could not find com.segunfamisa:icicle-processor:1.0.0.
Searched in the following locations:
    local file system
    https://dl.bintray.com/segunfamisa/maven/com/segunfamisa/icicle-processor/1.0.0/icicle-processor-1.0.0.pom
    https://dl.bintray.com/segunfamisa/maven/com/segunfamisa/icicle-processor/1.0.0/icicle-processor-1.0.0.jar
Required by:
    my-project-name:app:unspecified

**Comment by segunfamisa** [comment]
Hi @nielsdelporte , thanks for letting me know this.

I had a slight regression with the publishing. It's fixed now.
Please try again and let me know if it works.

It's now added to jCenter as well, so you may not need to add the 

```groovy
repositories {
    maven {
        url "https://dl.bintray.com/segunfamisa/maven/"
    }
}
```

I will update the readme shortly.

**Comment by nielsdelporte** [comment]
Hi @segunfamisa ,

You're welcome! Thanks for getting back to me so fast.
My gradle builds now, but I had to alter the configuration slightly.
The jcenter repository is not included in the project-level gradle file, since it alone is not sufficient to find Icicle (I have multiple repos configured, like jitpack.io).
I did have to include that block you mentioned though.
