### ISSUE TITLE
Icicle does not find superclasses with proguard enabled

### ISSUE THREAD

**Issue by nielsdelporte** [segunfamisa/icicle#9]
Hi,

I got Icicle working for my debug builds, for which I have disabled Proguard.
When I enable it, though, my logcat is filled with error messages like these: 

> E/Icicle: Not found...trying superclass

I have included Proguard rules, but to no avail.

```
# Icicle
-keepclasseswithmembers class com.segunfamisa.icicle.** { *; }
-keepclasseswithmembers class com.segunfamisa.icicle-processor.** { *; }
```

My gradle imports look like this:

```
//Icicle
compile 'com.segunfamisa:icicle:1.0.0'
apt 'com.segunfamisa:icicle-processor:1.0.0'
```

Any ideas on how I can fix this?
Enabling/disabling Proguard is the only difference between the two builds.

Thanks!

Full log:

> D/Icicle: Looking for icicle for: com.myapp.fragments.a.n
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> D/Icicle: Android or Java class detected...exiting
> D/Icicle: Looking for icicle for: com.myapp.fragments.a.m
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> D/Icicle: Android or Java class detected...exiting
> D/Icicle: Looking for icicle for: com.myapp.fragments.a.n
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> D/Icicle: Android or Java class detected...exiting
> D/Icicle: Looking for icicle for: com.myapp.fragments.a.m
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> D/Icicle: Android or Java class detected...exiting

**Comment by segunfamisa** [comment]
Hi @nielsdelporte ,

Thanks for bringing this up. This is a terrible, terrible oversight from me. I should have added this in the README. 

Please use the following proguard configuration:

```
-keep class **$$Icicle { *; }
-keep class com.segunfamisa.icicle.** { *; }
-keepclasseswithmembers class * {
    @com.segunfamisa.icicle.annotations.Freeze <fields>;
}
```

Please, let me know, if you're still having issues getting it working with Proguard.

**Comment by nielsdelporte** [comment]
Hi @segunfamisa ,

No problem, thanks for answering so fast!
I've applied the suggested proguard configuration, but I'm still having issues. Those might be related to my insufficient proficiency though.
The Fragments making use of Icicle are in another package, called feeds. That package is now readable, but I'm still getting similar error messages.

Do you have any suggestions for me?

> D/Icicle: Looking for icicle for: com.myapp.fragments.feeds.n
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> D/Icicle: Android or Java class detected...exiting
> D/Icicle: Looking for icicle for: com.myapp.fragments.feeds.m
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> D/Icicle: Android or Java class detected...exiting
> D/Icicle: Looking for icicle for: com.myapp.fragments.feeds.n
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> D/Icicle: Android or Java class detected...exiting
> I/art: After code cache collection, code=179KB, data=135KB
> D/Icicle: Looking for icicle for: com.myapp.fragments.feeds.m
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> E/Icicle: Not found...trying superclass
> D/Icicle: Android or Java class detected...exiting

**Comment by segunfamisa** [comment]
Hi, it looks like the Proguard configuration has not yet been applied.

I'm suspecting a problem with the way your Proguard configuration is setup.

If you need a referesher on configuring Proguard, you can check here:
https://github.com/codepath/android_guides/wiki/Configuring-ProGuard for how

Let me know if this persists after you confirm you're doing everything right.

Cheers.

**Comment by nielsdelporte** [comment]
Due to timing constraints, I have decided to forego Icicle and do everything manually as the number of variables I need upon restoring instance state is not that large.
Will come back to this issue when I've got some time to spare though.

Thanks for your help!
